In [1]:
import numpy as np
import sys
import pandas as pd

In [2]:
arr = np.array([1,2,3,4,5,10])

In [3]:
arr

array([ 1,  2,  3,  4,  5, 10])

In [4]:
arr[0:]

array([ 1,  2,  3,  4,  5, 10])

In [5]:
arr[1:-1]

array([2, 3, 4, 5])

In [6]:
arr2 = np.array([{'a':1},sys])

In [7]:
arr2

array([{'a': 1}, <module 'sys' (built-in)>], dtype=object)

In [8]:
arr3 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr3.sum(axis=0)

array([12, 15, 18])

In [10]:
arr3.sum(axis=1)

array([ 6, 15, 24])

In [11]:
arr3 > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [12]:
arr3[arr3 > 5]

array([6, 7, 8, 9])

In [16]:
pd.isnull(np.nan) #isna() can be also used

True

In [18]:
pd.isnull(None) #isna() can be also used. notnull() and notna() are the opposites

True

In [19]:
pd.isnull(pd.Series([1,2,np.nan,4]))

0    False
1    False
2     True
3    False
dtype: bool

In [20]:
pd.Series([1,2,5,np.nan,6]).count()

4

In [21]:
pd.Series([1,2,5,np.nan,6]).sum()

14.0

In [22]:
pd.Series([1,2,5,np.nan,6]).mean()

3.5

In [23]:
s = pd.Series([1,10,np.nan,4,np.nan,5,7,2,np.nan])
s

0     1.0
1    10.0
2     NaN
3     4.0
4     NaN
5     5.0
6     7.0
7     2.0
8     NaN
dtype: float64

In [25]:
s[pd.notnull(s)] #filtering the nan values

0     1.0
1    10.0
3     4.0
5     5.0
6     7.0
7     2.0
dtype: float64

In [28]:
s.dropna() #dropping nan values

0     1.0
1    10.0
3     4.0
5     5.0
6     7.0
7     2.0
dtype: float64

In [32]:
df = pd.DataFrame({
    'Column A': [1, np.nan, 30, np.nan],
    'Column B': [2, 8, 31, np.nan],
    'Column C': [np.nan, 9, 32, 100],
    'Column D': [5, 8, 34, 110],
})

df.shape

(4, 4)

In [33]:
df.isnull()

Column A  Column B  Column C  Column D
0     False     False      True     False
1      True     False     False     False
2     False     False     False     False
3      True      True     False     False

In [34]:
df.dropna() #by default, it is axis = 0

Column A  Column B  Column C  Column D
2      30.0      31.0      32.0        34

In [35]:
df.dropna(axis=1)

Column D
0         5
1         8
2        34
3       110

In [36]:
df2 = pd.DataFrame({
    'Column A': [1, np.nan, 30],
    'Column B': [2, np.nan, 31],
    'Column C': [np.nan, np.nan, 100]
})
df2

Column A  Column B  Column C
0       1.0       2.0       NaN
1       NaN       NaN       NaN
2      30.0      31.0     100.0

In [37]:
df2.dropna(how='all')

Column A  Column B  Column C
0       1.0       2.0       NaN
2      30.0      31.0     100.0

In [38]:
df2.dropna(how='any') #by default

Column A  Column B  Column C
2      30.0      31.0     100.0

In [39]:
df.dropna(thresh=3) # min number of non-null values for to be kept

Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34

In [41]:
s.fillna(0) #fill nan with 0

0     1.0
1    10.0
2     0.0
3     4.0
4     0.0
5     5.0
6     7.0
7     2.0
8     0.0
dtype: float64

In [43]:
s.fillna(s.mean())

0     1.000000
1    10.000000
2     4.833333
3     4.000000
4     4.833333
5     5.000000
6     7.000000
7     2.000000
8     4.833333
dtype: float64

In [45]:
s.fillna(method='bfill')

<ipython-input-45-3624d7f4ebdb>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  s.fillna(method='bfill')


0     1.0
1    10.0
2     4.0
3     4.0
4     5.0
5     5.0
6     7.0
7     2.0
8     NaN
dtype: float64

In [53]:
df2 = pd.DataFrame({
    'Sex': ['M','F','F','R','?'],
    'Age': [29,30,24,290,25]
})
df2

Sex  Age
0   M   29
1   F   30
2   F   24
3   R  290
4   ?   25

In [54]:
df2['Sex'].unique()

array(['M', 'F', 'R', '?'], dtype=object)

In [55]:
df2.Sex.value_counts()

Sex
F    2
M    1
R    1
?    1
Name: count, dtype: int64

In [56]:
df2.replace({
    'Sex': {
        'R': 'F',
        'N': 'M'
    },
    'Age': {
        290:29
    }
})

Sex  Age
0   M   29
1   F   30
2   F   24
3   F   29
4   ?   25

In [62]:
df2.loc[df2.Age > 100, 'Age'] = df2.loc[df2.Age > 100,'Age'] / 10
df2

Sex  Age
0   M   29
1   F   30
2   F   24
3   R   29
4   ?   25

In [65]:
ambassadors = pd.Series([
    'France',
    'United Kingdom',
    'United Kingdom',
    'Italy',
    'Germany',
    'Germany',
    'Germany',
], index=[
    'Gérard Araud',
    'Kim Darroch',
    'Peter Westmacott',
    'Armando Varricchio',
    'Peter Wittig',
    'Peter Ammon',
    'Klaus Scharioth '
])
ambassadors

Gérard Araud                  France
Kim Darroch           United Kingdom
Peter Westmacott      United Kingdom
Armando Varricchio             Italy
Peter Wittig                 Germany
Peter Ammon                  Germany
Klaus Scharioth              Germany
dtype: object

In [64]:
ambassadors.duplicated() # first occurrence is considered as non-duplicate. it can be changed with (keep='last')

Gérard Araud          False
Kim Darroch           False
Peter Westmacott       True
Armando Varricchio    False
Peter Wittig          False
Peter Ammon            True
Klaus Scharioth        True
dtype: bool

In [66]:
ambassadors.drop_duplicates()

Gérard Araud                  France
Kim Darroch           United Kingdom
Armando Varricchio             Italy
Peter Wittig                 Germany
dtype: object

In [67]:
ambassadors.drop_duplicates(keep=False) #mark all duplicates

Gérard Araud          France
Armando Varricchio     Italy
dtype: object

In [93]:
df3 = pd.DataFrame({
    'Data': [
        '1987_M_US _1',
        '1990?_M_UK_1',
        '1992_F_US_2',
        '1970?_M_   IT_1',
        '1985_F_I  T_2'
]})
df3

Data
0     1987_M_US _1
1     1990?_M_UK_1
2      1992_F_US_2
3  1970?_M_   IT_1
4    1985_F_I  T_2

In [94]:
df3 = df3.Data.str.split('_',expand=True)
df3

0  1      2  3
0   1987  M    US   1
1  1990?  M     UK  1
2   1992  F     US  2
3  1970?  M     IT  1
4   1985  F   I  T  2

In [95]:
df3.columns = ['Year','Sex','Country','# children']
df3

Year Sex Country # children
0   1987   M     US           1
1  1990?   M      UK          1
2   1992   F      US          2
3  1970?   M      IT          1
4   1985   F    I  T          2

In [97]:
df3.Country = df3.Country.str.replace(' ', '')
df3

Year Sex Country # children
0   1987   M      US          1
1  1990?   M      UK          1
2   1992   F      US          2
3  1970?   M      IT          1
4   1985   F      IT          2

In [98]:
df3.Year = df3.Year.str.replace('?','')
df3

Year Sex Country # children
0  1987   M      US          1
1  1990   M      UK          1
2  1992   F      US          2
3  1970   M      IT          1
4  1985   F      IT          2