
Importing libraries

In [2]:
import numpy as np
import sys

Constructing arrays

In [12]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [12]:
#get dimensions
a.ndim

1

In [13]:
#get shape
a.shape

(3,)

In [18]:
#get type
a.dtype

dtype('int16')

In [19]:
#get item size (one item)
a.itemsize

2

In [22]:
#get total size
a.size * a.itemsize

6

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones((2,2,3,4), dtype='int32')

array([[[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]],


       [[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]]], dtype=int32)

In [7]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [14]:
np.full_like(a, 4)

array([4, 4, 4], dtype=int16)

In [15]:
np.random.rand(4,2)

array([[0.49000815, 0.94571416],
       [0.3435323 , 0.64030385],
       [0.6616742 , 0.43801723],
       [0.02766466, 0.09398266]])

In [18]:
np.random.randint(7,size=(3,3)) #from 0 to 7 (except 7)

array([[1, 0, 1],
       [0, 2, 6],
       [5, 5, 4]])

In [19]:
np.random.randint(4,7,size=(3,3)) #from 4 to 7 (inc. 4, except 7)

array([[5, 6, 5],
       [4, 5, 5],
       [5, 4, 5]])

In [20]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3)
print(r1)

r2 = np.repeat(arr,3,axis=0)
print(r2)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [47]:
x = np.ones((5,5))
y = np.zeros((3,3))
y[1,1] = 9

x[1:4,1:4] = y
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [52]:
# when copying an array, do not use assignment like b = a. use b = a.copy() instead
a = np.array([2,4,6])
b = a.copy()
b[0] = 100
print(a)

[2 4 6]


In [55]:
# for mathematical operations (+,-,*,/,**) these operations will be applied to all elements
a = np.array([1,2,3,4])
print(a+2)
print(a-2)
print(a*2)
print(a/2)
print(a**2)

b = np.array([5,6,7,8])
print(a+b)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[ 6  8 10 12]


In [59]:
a = np.ones((2,3))
b = np.full((3,2),2)
print(a)
print(b)

c = np.matmul(a,b)
print(c)
np.linalg.det(c) # determinant

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


0.0

In [66]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)
np.min(stats)

[[1 2 3]
 [4 5 6]]


1

In [67]:
np.max(stats,axis=1)

array([3, 6])

In [69]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [73]:
before = np.array([[1,2,3,4],[5,6,7,8]])
after = before.reshape(4,2)
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [76]:
v1 = np.array([1,2,3,4])
v2 = np.array([2,3,4,5])
v3 = np.array([3,4,5,6])
v4 = np.array([4,5,7,8])

v5 = np.vstack([v1,v2,v3,v4]) #vertical stack
print(v5)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 7 8]]


In [80]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])